# -*- coding: utf-8 -*-
"""combine_both_output_csv files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsvK8YlVd6njGNGuRV24ImXx0PJ4-0F0
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df_exp_file_category = pd.read_csv('/content/drive/MyDrive/ZS_Data_Challenge/exp_file_category.csv')
df_exp_file_job_type = pd.read_csv('/content/drive/MyDrive/ZS_Data_Challenge/exp_file_job_type.csv')

output1 = pd.merge(df_exp_file_category, df_exp_file_job_type, 
                   on='job_no', 
                   how='inner')
print(output1)

output1.rename(columns = {'job_type_prediction_x':'category', 'job_type_prediction_y':'job_type',}, inplace = True)
print(output1)

output1.to_csv('/content/drive/MyDrive/ZS_Data_Challenge/submission.csv',index=False )